version: '3.5'

services: 
  frontend:
    image: 011092295y/frontend_example
    build: ../../docker_part1/1_10/.
    environment: 
      - API_URL=http://localhost:8000
    ports: 
      - 5000:5000
  
  backend:
    image: 011092295y/backend_example
    build: ../../docker_part1/1_11/.
    environment: 
      - FRONT_URL=http://localhost:5000
    ports: 
      - 8000:8000