version: '3.5'

services: 
  frontend:
    image: 011092295y/ml-kurkkumopo-frontend
    build: ./ml-kurkkumopo-frontend/.
    ports: 
      - 3000:3000
    container_name: ml-frontend

  backend:
    image: 011092295y/ml-kurkkumopo-backend
    build: ./ml-kurkkumopo-backend/.
    volumes: 
      - /src/model:/src/model
    container_name: ml-backend
    depends_on: 
      - training

  training:
    image: 011092295y/ml-kurkkumopo-training
    build: ./ml-kurkkumopo-training/.
    volumes: 
      - /src/model:/src/model
      - /src/imgs:/src/imgs
      - /src/data:/src/data
    container_name: ml-training