version: '3.5'

services: 
  frontend:
    image: 011092295y/frontend_example
    build: ../../docker_part1/1_10/.
    ports: 
      - 5000:5000
    environment: 
      - API_URL=/api

  backend:
    image: 011092295y/backend_example
    build: ../../docker_part1/1_11/.
    ports: 
      - 8000:8000
    environment: 
      - REDIS=redis
      - DB_USERNAME=postgres
      - DB_PASSWORD=example
      - DB_NAME=DB_EXAMPLE
      - DB_HOST=db
    volumes: 
      - ./logs.txt:/mydir/logs.txt
    depends_on: 
      - db

  redis:
    image: redis
    restart: unless-stopped
    volumes: 
      - /docker/host/dir:/data

  db:
    image: postgres
    restart: unless-stopped
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=DB_EXAMPLE

  reverse-proxy:
    image: nginx
    ports: 
      - 80:80
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on: 
      - frontend
      - backend